### ISSUE TITLE
Write better commit messages.

### ISSUE THREAD

**Issue by svalordev** [PyTweet/Tweety#1]
lol.

**Comment by shaurya-blip** [comment]
lol

**Comment by shaurya-blip** [comment]
LoL

**Comment by shaurya-blip** [comment]
lOl

**Comment by shaurya-blip** [comment]
LOL

**Comment by shaurya-blip** [comment]
LOl

**Comment by shaurya-blip** [comment]
lOL

**Comment by shaurya-blip** [comment]
lol

**Comment by Genoinno** [comment]
Will try! Sometimes i felt in a bad mood when making tweety!

**Comment by shaurya-blip** [comment]
> Will try! Sometimes i felt in a bad mood when making tweety!

Everyone does that. To prevent that, I don't commit at all.

**Comment by Genoinno** [comment]
> Everyone does that. To prevent that, I don't commit at all.
i have to commit, just with better message

**Comment by shaurya-blip** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
